/* The common language.
 *
 * Samsara calls it a vehicle. Geotab calls it a device. Maximo calls it an
 * asset. Fleetio calls it a unit. Every one of them uses different field
 * names, different id formats and a different way of paging through results.
 *
 * A connector's only job is to turn its own system's shape into the shapes
 * below. Nothing downstream — not the sync, not the database, not Guardian —
 * knows or cares where a vehicle came from.
 *
 * Getting this layer right is the hard part and the valuable part. A
 * connector is a few weeks of ordinary work; deciding what "a trip" means
 * when four systems each define it differently is the thing that has to hold
 * up as more systems are added.
 *
 * Rules for these shapes:
 *   - Only fields we can actually populate from a real system.
 *   - Anything a provider might not have is optional, not guessed at.
 *   - externalId is always the provider's own id, untouched. It is the only
 *     thing that lets a second sync update a record instead of duplicating it.
 */

/** A vehicle, as every provider will eventually be translated into. */
export interface CanonicalVehicle {
  /** The provider's id, exactly as they send it. Never generated by us. */
  externalId: string;
  name: string;
  /** Free text. Mapped onto VEHICLE_TYPE_GROUPS where a sensible match exists. */
  type?: string;
  registration?: string;
  vin?: string;
  make?: string;
  model?: string;
  year?: string;
  fuelType?: string;
  /** Odometer in miles, if the provider reports one. */
  odometerMiles?: number;
  status?: "active" | "maintenance" | "inactive" | "retired";
  /**
   * Which site this vehicle belongs to, as the provider records it.
   *
   * Every telematics system groups vehicles somehow — Samsara has tags, Geotab
   * has groups, Motive has groups — because that is how a real fleet tracks
   * which yard a truck lives at. Opservor was ignoring all of it and inferring
   * the depot by matching a trip's starting address against a warehouse site's
   * name, exactly. That match almost never succeeds on real data, which is why
   * the capacity check has never fired outside a seeded demo.
   *
   * Taken from the provider verbatim, not normalised. Matching it to a
   * warehouse site is the sync's problem, not the connector's.
   */
  depot?: string;
  /** Anything the provider sent that we have not mapped. Kept for debugging. */
  raw?: Record<string, unknown>;
}

/** A completed journey. */
export interface CanonicalTrip {
  externalId: string;
  /** The provider's vehicle id — resolved to ours during the sync. */
  vehicleExternalId: string;
  /** YYYY-MM-DD. */
  date: string;
  distanceMiles: number;
  fuelUsed?: number;
  origin?: string;
  destination?: string;
  status?: "completed" | "in_progress" | "cancelled";
  raw?: Record<string, unknown>;
}

/**
 * A booked or completed piece of service work.
 *
 * Worth being clear about what this is not. Telematics systems report driver
 * inspections and fault codes — a vehicle is defective *now*. That is a
 * different fact from a vehicle being *booked in* for Thursday, and only the
 * second one lets the capacity check see a clash coming. Scheduled work lives
 * in maintenance systems, which is why this shape exists and why the first
 * connector to fill it is not one of the telematics three.
 */
export interface CanonicalMaintenance {
  externalId: string;
  vehicleExternalId: string;
  /** Free text — "Oil change", "Brake inspection". Providers rarely agree. */
  type: string;
  status: "scheduled" | "in_progress" | "completed" | "cancelled";
  /** YYYY-MM-DD. The date the work is due or booked for. */
  scheduledDate?: string;
  /** YYYY-MM-DD. Required by the database when status is completed. */
  completedDate?: string;
  odometerMiles?: number;
  cost?: number;
  vendor?: string;
  reference?: string;
  notes?: string;
  raw?: Record<string, unknown>;
}

/**
 * A stock item, as an inventory system holds it.
 *
 * On quantities, and this is the part that matters. Opservor keeps
 * inventory_sku.quantity_on_hand in step with the movement ledger by trigger:
 * every outbound row moves the level. So an adapter that writes a level
 * directly is fighting the trigger, and the loser is whichever wrote last.
 *
 * The rule the sync applies: a level from a provider is accepted for an item
 * that has no movements recorded, because then nothing else is maintaining it.
 * Once movements exist, the ledger owns the number and the provider's figure is
 * ignored. Writing both is how 28 on hand became -602.
 */
export interface CanonicalItem {
  externalId: string;
  /** The customer's own code. Unique per company, not globally. */
  sku: string;
  name: string;
  category?: string;
  quantityOnHand: number;
  quantityReserved?: number;
  reorderLevel?: number;
  reorderQuantity?: number;
  unitCost?: number;
  unitPrice?: number;
  supplier?: string;
  raw?: Record<string, unknown>;
}

/** What a connector reports back after a fetch. */
export interface FetchResult<T> {
  items: T[];
  /** Pass back on the next call to continue. Absent means there is no more. */
  cursor?: string;
  /** Non-fatal problems — a row we could not translate, say. */
  warnings?: string[];
}

export interface ConnectorConfig {
  /** Overridable so a connection can point at a region, or at a stand-in. */
  baseUrl: string;
  /** Supplied at run time, server-side. Never read from the database. */
  token: string;
  /** Provider-specific extras — Geotab needs a database name, for example. */
  extra?: Record<string, string>;
}

/**
 * Every provider implements this and nothing more. Adding one means writing
 * these methods; it means changing nothing else.
 */
export interface Connector {
  readonly provider: string;
  /** Cheap call used to check credentials before a full sync. */
  verify(cfg: ConnectorConfig): Promise<{ ok: boolean; message: string }>;
  /**
   * Optional, and it took a fourth kind of system to notice.
   *
   * This was required, which quietly asserted that every system worth
   * connecting to is a fleet system. Three telematics providers and a
   * maintenance provider all had vehicles, so the assumption held by accident.
   * An inventory system has none, and making it return an empty list to satisfy
   * a signature would be a lie told to a type.
   */
  fetchVehicles?(cfg: ConnectorConfig, cursor?: string): Promise<FetchResult<CanonicalVehicle>>;
  /** Optional — not every provider exposes trips. */
  fetchTrips?(
    cfg: ConnectorConfig,
    since: string,
    cursor?: string
  ): Promise<FetchResult<CanonicalTrip>>;
  /** Optional — only maintenance systems have scheduled work. */
  fetchMaintenance?(
    cfg: ConnectorConfig,
    cursor?: string
  ): Promise<FetchResult<CanonicalMaintenance>>;
  /** Optional — inventory and ERP systems hold stock; telematics does not. */
  fetchItems?(
    cfg: ConnectorConfig,
    cursor?: string
  ): Promise<FetchResult<CanonicalItem>>;
}

/** Outcome of a sync, for the connection record and the screen. */
export interface SyncSummary {
  provider: string;
  vehiclesSeen: number;
  vehiclesCreated: number;
  vehiclesUpdated: number;
  tripsSeen: number;
  tripsCreated: number;
  maintenanceSeen: number;
  maintenanceCreated: number;
  itemsSeen: number;
  itemsCreated: number;
  itemsUpdated: number;
  warnings: string[];
  errors: string[];
  startedAt: string;
  finishedAt: string;
}
